-- Active: 1654277190001@@127.0.0.1@3307
use chatty;
CREATE OR REPLACE TABLE `message_chunks` (
  `ref` CHAR(60) PRIMARY KEY NOT NULL,
  `content` VARCHAR(255) NOT NULL
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `media`(
  `ref` CHAR(60) PRIMARY KEY NOT NULL,
  `url` VARCHAR(512) NOT NULL
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `messages` (
  `id` CHAR(30) PRIMARY KEY NOT NULL,
  `author` CHAR(30) NOT NULL,
  `channel` CHAR(30) NOT NULL,
  `content_ref` CHAR(60) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pinned` BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `status` (
  `user` CHAR(30) PRIMARY KEY NOT NULL,
  `emoji` INT DEFAULT NULL,
  `content` VARCHAR(64) DEFAULT NULL,
  `game_id` CHAR(30) DEFAULT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `games` (
  `game_id` CHAR(30) PRIMARY KEY NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `display_date` BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `friends` (
  `user` CHAR(30) PRIMARY KEY NOT NULL,
  `friend` CHAR(30) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pinned` BOOLEAN NOT NULL DEFAULT 0,
  `accepted` BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `users` (
  `id` CHAR(30) PRIMARY KEY NOT NULL,
  `email` VARCHAR(350) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `token` CHAR(64) NOT NULL,
  `creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(32) NOT NULL,
  `permissions` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `accept_friends_request` INT NOT NULL DEFAULT 2, 
  `system` BOOLEAN NOT NULL DEFAULT 0,
  `disabled` BOOLEAN NOT NULL DEFAULT 0,
  `xp` INT NOT NULL DEFAULT 0,
  `lvl` INT NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;
/* 2 = all, 1 = only from friends, 0 = NOPE */
CREATE OR REPLACE TABLE `channel_users` (
  `channel` CHAR(30) PRIMARY KEY NOT NULL,
  `user` CHAR(30) NOT NULL,
  `permissions` BIGINT NOT NULL DEFAULT 0,
  `admin_channel` BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `channels` (
  `id` CHAR(30) PRIMARY KEY NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `public` BOOLEAN NOT NULL,
  `system` BOOLEAN NOT NULL DEFAULT 0,
  `admin` BOOLEAN NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `ban` (
  `user` CHAR(30) PRIMARY KEY NOT NULL,
  `ip` VARCHAR(40) DEFAULT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `duration` INT UNSIGNED NOT NULL,
  `reason` VARCHAR(1024) NOT NULL,
  `author` CHAR(30) NOT NULL
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `admin_channels` (
  `channel` CHAR(30) NOT NULL,
  `access_code` CHAR(32) NOT NULL
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `admin` (
  `admin_id` CHAR(16) PRIMARY KEY NOT NULL,
  `user` CHAR(30) NOT NULL,
  `permissions` BIGINT NOT NULL DEFAULT 0,
  `admin_creation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sec_pin` CHAR(32) NOT NULL
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `system_access` (
  `admin` CHAR(16) PRIMARY KEY NOT NULL,
  `code` CHAR(32) NOT NULL,
  `ref` VARCHAR(128) NOT NULL
) DEFAULT CHARSET=utf8;
CREATE OR REPLACE TABLE `access_logs` (
  `id` CHAR(128) PRIMARY KEY NOT NULL,
  `ref` VARCHAR(128) NOT NULL,
  `admin` CHAR(16) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `details` VARCHAR(512) NOT NULL
) DEFAULT CHARSET=utf8;